version: '3.9'

services:
  db:
    image: postgres:15-alpine
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-filmdb}
      POSTGRES_USER: ${POSTGRES_USER:-film_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-film_password}
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://film_user:film_password@db:5432/filmdb}
      JWT_SECRET: ${JWT_SECRET:-supersecret}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-supersecretrefresh}
      DEFAULT_ALLOW_REGISTRATION: ${DEFAULT_ALLOW_REGISTRATION:-true}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN:-http://localhost:5173}
      PORT: ${PORT:-4000}
    ports:
      - '4000:4000'
    command: >-
      sh -c "./scripts/wait-for-db.sh && npm run migrate && npm run seed && npm run start"

  web:
    build:
      context: ./frontend
    depends_on:
      - api
    ports:
      - '5173:80'

volumes:
  db-data:
